name = "notion-widget"
main = "worker.js"
compatibility_date = "2026-07-26"
workers_dev = true
keep_vars = true

[vars]
NOTION_READING_BOOKS_DATA_SOURCE_ID = "519b993c-8a61-8222-b574-073c2e3ab536"
NOTION_READING_QUOTES_DATA_SOURCE_ID = "98cb993c-8a61-8282-a92c-873a237dda11"
NOTION_READING_YEARS_DATA_SOURCE_ID = "854b993c-8a61-8333-a37c-07c186deda8e"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "notion_widget_db"
database_id = "319c978c-10dd-425f-b344-233fbbf2fd8d"

[[kv_namespaces]]
binding = "KV"
id = "3c209fa8f0514df9b18667f042bb3f5f"
